#############################################################################
# Makefile for building: libSWMMComponent.1.0.0.dylib
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  SWMMComponent.pro
# Template: lib
# Command: /Users/calebbuahin/Qt5.6.0/5.6/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SWMMComponent.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DSWMMCOMPONENT_LIBRARY -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -Iinclude -I../HydroCouple/include -I../HydroCoupleSDK/include -I/usr/local/include -I/usr/local/include/libiomp -I../../../../Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -Ibuild/debug/.moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang -F/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib
QMAKE         = /Users/calebbuahin/Qt5.6.0/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SWMMComponent1.0.0
DISTDIR = /Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent/build/debug/.obj/SWMMComponent1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib -single_module -dynamiclib -compatibility_version	1.0 -current_version	1.0.0 -install_name	libSWMMComponent.1.dylib
LIBS          = $(SUBLIBS) -F/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib -L/usr/local/lib/ -liomp5 -L./../HydroCoupleSDK/build/debug -lHydroCoupleSDK.1.0.0 -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = build/debug/.obj/

####### Files

SOURCES       = src/climate.c \
		src/controls.c \
		src/culvert.c \
		src/datetime.c \
		src/dwflow.c \
		src/dynwave.c \
		src/error.c \
		src/exfil.c \
		src/findroot.c \
		src/flowrout.c \
		src/forcmain.c \
		src/gage.c \
		src/gwater.c \
		src/hash.c \
		src/hotstart.c \
		src/iface.c \
		src/infil.c \
		src/inflow.c \
		src/input.c \
		src/inputrpt.c \
		src/keywords.c \
		src/kinwave.c \
		src/landuse.c \
		src/lid.c \
		src/lidproc.c \
		src/link.c \
		src/massbal.c \
		src/mathexpr.c \
		src/mempool.c \
		src/node.c \
		src/odesolve.c \
		src/output.c \
		src/project.c \
		src/qualrout.c \
		src/rain.c \
		src/rdii.c \
		src/report.c \
		src/roadway.c \
		src/routing.c \
		src/runoff.c \
		src/shape.c \
		src/snow.c \
		src/stats.c \
		src/statsrpt.c \
		src/stdafx.cpp \
		src/subcatch.c \
		src/surfqual.c \
		src/swmm5.c \
		src/swmmcomponent.cpp \
		src/table.c \
		src/toposort.c \
		src/transect.c \
		src/treatmnt.c \
		src/xsect.c \
		src/dataexchangecache.cpp \
		src/swmmmodelcomponentinfo.cpp \
		src/swmmtimeseriesexchangeitems.cpp build/debug/.moc/moc_swmmcomponent.cpp \
		build/debug/.moc/moc_swmmmodelcomponentinfo.cpp \
		build/debug/.moc/moc_swmmtimeseriesexchangeitems.cpp
OBJECTS       = build/debug/.obj/climate.o \
		build/debug/.obj/controls.o \
		build/debug/.obj/culvert.o \
		build/debug/.obj/datetime.o \
		build/debug/.obj/dwflow.o \
		build/debug/.obj/dynwave.o \
		build/debug/.obj/error.o \
		build/debug/.obj/exfil.o \
		build/debug/.obj/findroot.o \
		build/debug/.obj/flowrout.o \
		build/debug/.obj/forcmain.o \
		build/debug/.obj/gage.o \
		build/debug/.obj/gwater.o \
		build/debug/.obj/hash.o \
		build/debug/.obj/hotstart.o \
		build/debug/.obj/iface.o \
		build/debug/.obj/infil.o \
		build/debug/.obj/inflow.o \
		build/debug/.obj/input.o \
		build/debug/.obj/inputrpt.o \
		build/debug/.obj/keywords.o \
		build/debug/.obj/kinwave.o \
		build/debug/.obj/landuse.o \
		build/debug/.obj/lid.o \
		build/debug/.obj/lidproc.o \
		build/debug/.obj/link.o \
		build/debug/.obj/massbal.o \
		build/debug/.obj/mathexpr.o \
		build/debug/.obj/mempool.o \
		build/debug/.obj/node.o \
		build/debug/.obj/odesolve.o \
		build/debug/.obj/output.o \
		build/debug/.obj/project.o \
		build/debug/.obj/qualrout.o \
		build/debug/.obj/rain.o \
		build/debug/.obj/rdii.o \
		build/debug/.obj/report.o \
		build/debug/.obj/roadway.o \
		build/debug/.obj/routing.o \
		build/debug/.obj/runoff.o \
		build/debug/.obj/shape.o \
		build/debug/.obj/snow.o \
		build/debug/.obj/stats.o \
		build/debug/.obj/statsrpt.o \
		build/debug/.obj/stdafx.o \
		build/debug/.obj/subcatch.o \
		build/debug/.obj/surfqual.o \
		build/debug/.obj/swmm5.o \
		build/debug/.obj/swmmcomponent.o \
		build/debug/.obj/table.o \
		build/debug/.obj/toposort.o \
		build/debug/.obj/transect.o \
		build/debug/.obj/treatmnt.o \
		build/debug/.obj/xsect.o \
		build/debug/.obj/dataexchangecache.o \
		build/debug/.obj/swmmmodelcomponentinfo.o \
		build/debug/.obj/swmmtimeseriesexchangeitems.o \
		build/debug/.obj/moc_swmmcomponent.o \
		build/debug/.obj/moc_swmmmodelcomponentinfo.o \
		build/debug/.obj/moc_swmmtimeseriesexchangeitems.o
DIST          = ../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/lex.prf \
		SWMMComponent.pro include/consts.h \
		include/datetime.h \
		include/enums.h \
		include/error.h \
		include/exfil.h \
		include/findroot.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/headers.h \
		include/infil.h \
		include/keywords.h \
		include/lid.h \
		include/macros.h \
		include/mathexpr.h \
		include/mempool.h \
		include/objects.h \
		include/odesolve.h \
		include/stdafx.h \
		include/swmm5.h \
		include/swmmcomponent.h \
		include/swmmcomponent_global.h \
		include/text.h \
		include/swmmmodelcomponentinfo.h \
		include/dataexchangecache.h \
		include/swmmobjectitems.h \
		include/swmmtimeseriesexchangeitems.h src/climate.c \
		src/controls.c \
		src/culvert.c \
		src/datetime.c \
		src/dwflow.c \
		src/dynwave.c \
		src/error.c \
		src/exfil.c \
		src/findroot.c \
		src/flowrout.c \
		src/forcmain.c \
		src/gage.c \
		src/gwater.c \
		src/hash.c \
		src/hotstart.c \
		src/iface.c \
		src/infil.c \
		src/inflow.c \
		src/input.c \
		src/inputrpt.c \
		src/keywords.c \
		src/kinwave.c \
		src/landuse.c \
		src/lid.c \
		src/lidproc.c \
		src/link.c \
		src/massbal.c \
		src/mathexpr.c \
		src/mempool.c \
		src/node.c \
		src/odesolve.c \
		src/output.c \
		src/project.c \
		src/qualrout.c \
		src/rain.c \
		src/rdii.c \
		src/report.c \
		src/roadway.c \
		src/routing.c \
		src/runoff.c \
		src/shape.c \
		src/snow.c \
		src/stats.c \
		src/statsrpt.c \
		src/stdafx.cpp \
		src/subcatch.c \
		src/surfqual.c \
		src/swmm5.c \
		src/swmmcomponent.cpp \
		src/table.c \
		src/toposort.c \
		src/transect.c \
		src/treatmnt.c \
		src/xsect.c \
		src/dataexchangecache.cpp \
		src/swmmmodelcomponentinfo.cpp \
		src/swmmtimeseriesexchangeitems.cpp
QMAKE_TARGET  = SWMMComponent
DESTDIR       = build/debug/
TARGET        = libSWMMComponent.1.0.0.dylib
TARGETA       = build/debug/libSWMMComponent.a
TARGET0       = libSWMMComponent.dylib
TARGETD       = libSWMMComponent.1.0.0.dylib
TARGET1       = libSWMMComponent.1.dylib
TARGET2       = libSWMMComponent.1.0.dylib


first: all
####### Build rules

build/debug/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d build/debug/ || mkdir -p build/debug/
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) build/debug/$(TARGET)
	-$(MOVE) $(TARGET)  build/debug/ 
	-$(DEL_FILE) build/debug/$(TARGET0)
	-$(DEL_FILE) build/debug/$(TARGET1)
	-$(DEL_FILE) build/debug/$(TARGET2)
	-$(MOVE) $(TARGET0) build/debug/ 
	-$(MOVE) $(TARGET1) build/debug/ 
	-$(MOVE) $(TARGET2) build/debug/ 



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
	$(RANLIB) $(TARGETA)

Makefile: SWMMComponent.pro ../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/lex.prf \
		SWMMComponent.pro \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SWMMComponent.pro
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/qdevice.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/device_config.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/unix.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/mac.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/macx.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/qconfig.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/default_post.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/qt.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/resources.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/moc.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/yacc.prf:
../../../../Qt5.6.0/5.6/clang_64/mkspecs/features/lex.prf:
SWMMComponent.pro:
../../../../Qt5.6.0/5.6/clang_64/lib/QtGui.framework/QtGui.prl:
../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SWMMComponent.pro

qmake_all: FORCE


all: Makefile build/debug/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/consts.h include/datetime.h include/enums.h include/error.h include/exfil.h include/findroot.h include/funcs.h include/globals.h include/hash.h include/headers.h include/infil.h include/keywords.h include/lid.h include/macros.h include/mathexpr.h include/mempool.h include/objects.h include/odesolve.h include/stdafx.h include/swmm5.h include/swmmcomponent.h include/swmmcomponent_global.h include/text.h include/swmmmodelcomponentinfo.h include/dataexchangecache.h include/swmmobjectitems.h include/swmmtimeseriesexchangeitems.h $(DISTDIR)/
	$(COPY_FILE) --parents src/climate.c src/controls.c src/culvert.c src/datetime.c src/dwflow.c src/dynwave.c src/error.c src/exfil.c src/findroot.c src/flowrout.c src/forcmain.c src/gage.c src/gwater.c src/hash.c src/hotstart.c src/iface.c src/infil.c src/inflow.c src/input.c src/inputrpt.c src/keywords.c src/kinwave.c src/landuse.c src/lid.c src/lidproc.c src/link.c src/massbal.c src/mathexpr.c src/mempool.c src/node.c src/odesolve.c src/output.c src/project.c src/qualrout.c src/rain.c src/rdii.c src/report.c src/roadway.c src/routing.c src/runoff.c src/shape.c src/snow.c src/stats.c src/statsrpt.c src/stdafx.cpp src/subcatch.c src/surfqual.c src/swmm5.c src/swmmcomponent.cpp src/table.c src/toposort.c src/transect.c src/treatmnt.c src/xsect.c src/dataexchangecache.cpp src/swmmmodelcomponentinfo.cpp src/swmmtimeseriesexchangeitems.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) build/debug/$(TARGET) 
	-$(DEL_FILE) build/debug/$(TARGET0) build/debug/$(TARGET1) build/debug/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: build/debug/.moc/moc_swmmcomponent.cpp build/debug/.moc/moc_swmmmodelcomponentinfo.cpp build/debug/.moc/moc_swmmtimeseriesexchangeitems.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/debug/.moc/moc_swmmcomponent.cpp build/debug/.moc/moc_swmmmodelcomponentinfo.cpp build/debug/.moc/moc_swmmtimeseriesexchangeitems.cpp
build/debug/.moc/moc_swmmcomponent.cpp: include/swmmcomponent_global.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/swmm5.h \
		../HydroCoupleSDK/include/abstractmodelcomponent.h \
		../HydroCoupleSDK/include/identity.h \
		../HydroCoupleSDK/include/description.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../HydroCoupleSDK/include/timedata.h \
		../HydroCouple/include/hydrocoupletemporal.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QDateTime \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../HydroCoupleSDK/include/idbasedargument.h \
		../HydroCoupleSDK/include/abstractargument.h \
		../HydroCoupleSDK/include/abstractcomponentdataitem.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../HydroCoupleSDK/include/idbasedcomponentdataitem.h \
		../HydroCoupleSDK/include/componentdataitem1d.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		include/swmmcomponent.h
	/Users/calebbuahin/Qt5.6.0/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/calebbuahin/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang -I/Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCouple/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCoupleSDK/include -I/usr/local/include -I/usr/local/include/libiomp -I/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib include/swmmcomponent.h -o build/debug/.moc/moc_swmmcomponent.cpp

build/debug/.moc/moc_swmmmodelcomponentinfo.cpp: include/swmmcomponent_global.h \
		../HydroCoupleSDK/include/modelcomponentinfo.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../HydroCoupleSDK/include/componentinfo.h \
		../HydroCoupleSDK/include/identity.h \
		../HydroCoupleSDK/include/description.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		include/swmmmodelcomponentinfo.h
	/Users/calebbuahin/Qt5.6.0/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/calebbuahin/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang -I/Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCouple/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCoupleSDK/include -I/usr/local/include -I/usr/local/include/libiomp -I/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib include/swmmmodelcomponentinfo.h -o build/debug/.moc/moc_swmmmodelcomponentinfo.cpp

build/debug/.moc/moc_swmmtimeseriesexchangeitems.cpp: include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/swmmcomponent_global.h \
		../HydroCoupleSDK/include/timeseriesexchangeitem.h \
		../HydroCoupleSDK/include/timeseriescomponentdataitem.h \
		../HydroCouple/include/hydrocoupletemporal.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../HydroCoupleSDK/include/componentdataitem1d.h \
		../HydroCoupleSDK/include/abstractcomponentdataitem.h \
		../HydroCoupleSDK/include/identity.h \
		../HydroCoupleSDK/include/description.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../HydroCoupleSDK/include/abstractinput.h \
		../HydroCoupleSDK/include/abstractexchangeitem.h \
		../HydroCoupleSDK/include/abstractoutput.h \
		include/swmmobjectitems.h \
		include/swmmtimeseriesexchangeitems.h
	/Users/calebbuahin/Qt5.6.0/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/calebbuahin/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang -I/Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent -I/Users/calebbuahin/Documents/Projects/HydroCouple/SWMMComponent/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCouple/include -I/Users/calebbuahin/Documents/Projects/HydroCouple/HydroCoupleSDK/include -I/usr/local/include -I/usr/local/include/libiomp -I/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/calebbuahin/Qt5.6.0/5.6/clang_64/lib include/swmmtimeseriesexchangeitems.h -o build/debug/.moc/moc_swmmtimeseriesexchangeitems.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/debug/.obj/climate.o: src/climate.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/climate.o src/climate.c

build/debug/.obj/controls.o: src/controls.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/controls.o src/controls.c

build/debug/.obj/culvert.o: src/culvert.c include/findroot.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/culvert.o src/culvert.c

build/debug/.obj/datetime.o: src/datetime.c include/datetime.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/datetime.o src/datetime.c

build/debug/.obj/dwflow.o: src/dwflow.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/dwflow.o src/dwflow.c

build/debug/.obj/dynwave.o: src/dynwave.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		/usr/local/include/libiomp/omp.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/dynwave.o src/dynwave.c

build/debug/.obj/error.o: src/error.c include/error.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/error.o src/error.c

build/debug/.obj/exfil.o: src/exfil.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/exfil.o src/exfil.c

build/debug/.obj/findroot.o: src/findroot.c include/findroot.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/findroot.o src/findroot.c

build/debug/.obj/flowrout.o: src/flowrout.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/flowrout.o src/flowrout.c

build/debug/.obj/forcmain.o: src/forcmain.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/forcmain.o src/forcmain.c

build/debug/.obj/gage.o: src/gage.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/gage.o src/gage.c

build/debug/.obj/gwater.o: src/gwater.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/odesolve.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/gwater.o src/gwater.c

build/debug/.obj/hash.o: src/hash.c include/hash.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/hash.o src/hash.c

build/debug/.obj/hotstart.o: src/hotstart.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/hotstart.o src/hotstart.c

build/debug/.obj/iface.o: src/iface.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/iface.o src/iface.c

build/debug/.obj/infil.o: src/infil.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/infil.o src/infil.c

build/debug/.obj/inflow.o: src/inflow.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/inflow.o src/inflow.c

build/debug/.obj/input.o: src/input.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/input.o src/input.c

build/debug/.obj/inputrpt.o: src/inputrpt.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/inputrpt.o src/inputrpt.c

build/debug/.obj/keywords.o: src/keywords.c include/text.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/keywords.o src/keywords.c

build/debug/.obj/kinwave.o: src/kinwave.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/findroot.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/kinwave.o src/kinwave.c

build/debug/.obj/landuse.o: src/landuse.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/landuse.o src/landuse.c

build/debug/.obj/lid.o: src/lid.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/lid.o src/lid.c

build/debug/.obj/lidproc.o: src/lidproc.c include/lid.h \
		include/infil.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/exfil.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/lidproc.o src/lidproc.c

build/debug/.obj/link.o: src/link.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/link.o src/link.c

build/debug/.obj/massbal.o: src/massbal.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/massbal.o src/massbal.c

build/debug/.obj/mathexpr.o: src/mathexpr.c include/mathexpr.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/mathexpr.o src/mathexpr.c

build/debug/.obj/mempool.o: src/mempool.c include/mempool.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/mempool.o src/mempool.c

build/debug/.obj/node.o: src/node.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/findroot.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/node.o src/node.c

build/debug/.obj/odesolve.o: src/odesolve.c include/odesolve.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/odesolve.o src/odesolve.c

build/debug/.obj/output.o: src/output.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/output.o src/output.c

build/debug/.obj/project.o: src/project.c /usr/local/include/libiomp/omp.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/mempool.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/project.o src/project.c

build/debug/.obj/qualrout.o: src/qualrout.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/qualrout.o src/qualrout.c

build/debug/.obj/rain.o: src/rain.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/rain.o src/rain.c

build/debug/.obj/rdii.o: src/rdii.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/rdii.o src/rdii.c

build/debug/.obj/report.o: src/report.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/report.o src/report.c

build/debug/.obj/roadway.o: src/roadway.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/roadway.o src/roadway.c

build/debug/.obj/routing.o: src/routing.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/routing.o src/routing.c

build/debug/.obj/runoff.o: src/runoff.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/odesolve.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/runoff.o src/runoff.c

build/debug/.obj/shape.o: src/shape.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/shape.o src/shape.c

build/debug/.obj/snow.o: src/snow.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/snow.o src/snow.c

build/debug/.obj/stats.o: src/stats.c /usr/local/include/libiomp/omp.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/stats.o src/stats.c

build/debug/.obj/statsrpt.o: src/statsrpt.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/statsrpt.o src/statsrpt.c

build/debug/.obj/stdafx.o: src/stdafx.cpp include/stdafx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/stdafx.o src/stdafx.cpp

build/debug/.obj/subcatch.o: src/subcatch.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/odesolve.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/subcatch.o src/subcatch.c

build/debug/.obj/surfqual.o: src/surfqual.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/surfqual.o src/surfqual.c

build/debug/.obj/swmm5.o: src/swmm5.c include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/swmm5.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/swmm5.o src/swmm5.c

build/debug/.obj/swmmcomponent.o: src/swmmcomponent.cpp include/stdafx.h \
		include/swmmcomponent.h \
		include/swmmcomponent_global.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/swmm5.h \
		../HydroCoupleSDK/include/abstractmodelcomponent.h \
		../HydroCoupleSDK/include/identity.h \
		../HydroCoupleSDK/include/description.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../HydroCoupleSDK/include/timedata.h \
		../HydroCouple/include/hydrocoupletemporal.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QDateTime \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../HydroCoupleSDK/include/idbasedargument.h \
		../HydroCoupleSDK/include/abstractargument.h \
		../HydroCoupleSDK/include/abstractcomponentdataitem.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../HydroCoupleSDK/include/idbasedcomponentdataitem.h \
		../HydroCoupleSDK/include/componentdataitem1d.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		include/swmmmodelcomponentinfo.h \
		../HydroCoupleSDK/include/modelcomponentinfo.h \
		../HydroCoupleSDK/include/componentinfo.h \
		../HydroCoupleSDK/include/dimension.h \
		../HydroCoupleSDK/include/valuedefinition.h \
		../HydroCoupleSDK/include/unit.h \
		include/swmmtimeseriesexchangeitems.h \
		../HydroCoupleSDK/include/timeseriesexchangeitem.h \
		../HydroCoupleSDK/include/timeseriescomponentdataitem.h \
		../HydroCoupleSDK/include/abstractinput.h \
		../HydroCoupleSDK/include/abstractexchangeitem.h \
		../HydroCoupleSDK/include/abstractoutput.h \
		include/swmmobjectitems.h \
		../HydroCoupleSDK/include/componentstatuschangeeventargs.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qdir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/swmmcomponent.o src/swmmcomponent.cpp

build/debug/.obj/table.o: src/table.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/table.o src/table.c

build/debug/.obj/toposort.o: src/toposort.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/toposort.o src/toposort.c

build/debug/.obj/transect.o: src/transect.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/transect.o src/transect.c

build/debug/.obj/treatmnt.o: src/treatmnt.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/treatmnt.o src/treatmnt.c

build/debug/.obj/xsect.o: src/xsect.c include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/findroot.h \
		src/xsect.dat
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/debug/.obj/xsect.o src/xsect.c

build/debug/.obj/dataexchangecache.o: src/dataexchangecache.cpp include/stdafx.h \
		include/dataexchangecache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/dataexchangecache.o src/dataexchangecache.cpp

build/debug/.obj/swmmmodelcomponentinfo.o: src/swmmmodelcomponentinfo.cpp include/stdafx.h \
		include/swmmmodelcomponentinfo.h \
		include/swmmcomponent_global.h \
		../HydroCoupleSDK/include/modelcomponentinfo.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../HydroCoupleSDK/include/componentinfo.h \
		../HydroCoupleSDK/include/identity.h \
		../HydroCoupleSDK/include/description.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		include/swmmcomponent.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/swmm5.h \
		../HydroCoupleSDK/include/abstractmodelcomponent.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../HydroCoupleSDK/include/timedata.h \
		../HydroCouple/include/hydrocoupletemporal.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QDateTime \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../HydroCoupleSDK/include/idbasedargument.h \
		../HydroCoupleSDK/include/abstractargument.h \
		../HydroCoupleSDK/include/abstractcomponentdataitem.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../HydroCoupleSDK/include/idbasedcomponentdataitem.h \
		../HydroCoupleSDK/include/componentdataitem1d.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QUuid \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/quuid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/swmmmodelcomponentinfo.o src/swmmmodelcomponentinfo.cpp

build/debug/.obj/swmmtimeseriesexchangeitems.o: src/swmmtimeseriesexchangeitems.cpp include/stdafx.h \
		include/swmmtimeseriesexchangeitems.h \
		include/headers.h \
		include/consts.h \
		include/macros.h \
		include/enums.h \
		include/error.h \
		include/datetime.h \
		include/objects.h \
		include/mathexpr.h \
		include/infil.h \
		include/exfil.h \
		include/lid.h \
		include/funcs.h \
		include/globals.h \
		include/hash.h \
		include/text.h \
		include/keywords.h \
		include/dataexchangecache.h \
		include/swmmcomponent_global.h \
		../HydroCoupleSDK/include/timeseriesexchangeitem.h \
		../HydroCoupleSDK/include/timeseriescomponentdataitem.h \
		../HydroCouple/include/hydrocoupletemporal.h \
		../HydroCouple/include/hydrocouple.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../HydroCoupleSDK/include/componentdataitem1d.h \
		../HydroCoupleSDK/include/abstractcomponentdataitem.h \
		../HydroCoupleSDK/include/identity.h \
		../HydroCoupleSDK/include/description.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../HydroCoupleSDK/include/hydrocouplesdk.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../HydroCoupleSDK/include/abstractinput.h \
		../HydroCoupleSDK/include/abstractexchangeitem.h \
		../HydroCoupleSDK/include/abstractoutput.h \
		include/swmmobjectitems.h \
		include/swmmcomponent.h \
		include/swmm5.h \
		../HydroCoupleSDK/include/abstractmodelcomponent.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../HydroCoupleSDK/include/timedata.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QDateTime \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../HydroCoupleSDK/include/idbasedargument.h \
		../HydroCoupleSDK/include/abstractargument.h \
		../HydroCoupleSDK/include/idbasedcomponentdataitem.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../HydroCoupleSDK/include/dimension.h \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/swmmtimeseriesexchangeitems.o src/swmmtimeseriesexchangeitems.cpp

build/debug/.obj/moc_swmmcomponent.o: build/debug/.moc/moc_swmmcomponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_swmmcomponent.o build/debug/.moc/moc_swmmcomponent.cpp

build/debug/.obj/moc_swmmmodelcomponentinfo.o: build/debug/.moc/moc_swmmmodelcomponentinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_swmmmodelcomponentinfo.o build/debug/.moc/moc_swmmmodelcomponentinfo.cpp

build/debug/.obj/moc_swmmtimeseriesexchangeitems.o: build/debug/.moc/moc_swmmtimeseriesexchangeitems.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_swmmtimeseriesexchangeitems.o build/debug/.moc/moc_swmmtimeseriesexchangeitems.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

