#ifndef SWMMCOMPONENT_GLOBAL_H
#define SWMMCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SWMMCOMPONENT_LIB
# define SWMMCOMPONENT_EXPORT Q_DECL_EXPORT
#else
# define SWMMCOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // SWMMCOMPONENT_GLOBAL_H
